# Generated by Django 5.2.1 on 2025-05-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_profile', '0002_remove_user_app_id_user_open_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecords',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='运动时间')),
                ('exercise_type', models.CharField(choices=[('running', '跑步'), ('walking', '竞走'), ('yoga', '瑜伽'), ('cycling', '骑车'), ('badminton', '羽毛球'), ('basketball', '篮球'), ('football', '足球'), ('swimming', '游泳')], max_length=20, verbose_name='运动类型')),
                ('duration', models.IntegerField(verbose_name='运动时长(分钟)')),
                ('distance', models.FloatField(null=True, verbose_name='运动距离(km)')),
                ('calorie', models.FloatField(null=True, verbose_name='消耗卡路里(kcal)')),
                ('verification_photo_url', models.URLField(blank=True, null=True, verbose_name='验证照片URL')),
                ('verification_status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '未通过')], default='pending', max_length=10, verbose_name='验证状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='web_profile.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'db_table': 'ExerciseRecords',
            },
        ),
    ]
