# Generated by Django 5.2.3 on 2025-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web_profile", "0003_remove_user_open_id_user_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("post_content", models.TextField()),
                ("post_time", models.DateTimeField(auto_now_add=True)),
                ("post_title", models.TextField(max_length=255)),
                ("post_image", models.JSONField(blank=True, default=None, null=True)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pass", "审核通过"),
                            ("pending", "审核中"),
                            ("fail", "审核未通过"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="web_profile.user",
                    ),
                ),
            ],
            options={
                "db_table": "SocialMediaPost",
                "ordering": ["-post_time"],
            },
        ),
    ]
