# Generated by Django 5.2.3 on 2025-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web_profile", "0003_remove_user_open_id_user_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseRecords",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("record_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("calorie", models.FloatField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("pass", "通过"), ("fail", "拒绝")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_exercise_records",
                        to="web_profile.user",
                    ),
                ),
            ],
            options={
                "db_table": "ExerciseRecords",
            },
        ),
        migrations.CreateModel(
            name="ExerciseReminders",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("reminder_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("reminder_days_of_week", models.CharField(max_length=8)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_profile.user",
                    ),
                ),
            ],
            options={
                "db_table": "ExerciseReminders",
            },
        ),
        migrations.CreateModel(
            name="ExerciseTargets",
            fields=[
                ("target_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "target_cycle",
                    models.CharField(
                        choices=[("day", "每日"), ("week", "每周"), ("month", "每月")],
                        max_length=10,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("锻炼时长", "锻炼时长"), ("燃烧卡路里", "燃烧卡路里")], max_length=10
                    ),
                ),
                ("target_duration", models.IntegerField(blank=True, null=True)),
                ("target_calorie", models.FloatField(blank=True, null=True)),
                (
                    "uid",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_profile.user",
                    ),
                ),
            ],
            options={
                "db_table": "ExerciseTargets",
                "ordering": ["-target_id"],
            },
        ),
    ]
