# Generated by Django 5.2.3 on 2025-06-17 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "interact_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="交互ID"
                    ),
                ),
                ("uid", models.IntegerField(verbose_name="用户ID")),
                ("post_id", models.IntegerField(verbose_name="帖子ID")),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="interact_time",
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
            ],
            options={
                "verbose_name": "社交评论",
                "verbose_name_plural": "社交评论",
                "db_table": "SocialCommentInteraction",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
