# Generated by Django 5.2.3 on 2025-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseTarget",
            fields=[
                ("target_id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.IntegerField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[("duration", "Duration"), ("calorie", "Calorie")],
                        default="duration",
                        max_length=8,
                    ),
                ),
                (
                    "target_cycle",
                    models.CharField(
                        choices=[("day", "day"), ("week", "week"), ("month", "month")],
                        default="day",
                        max_length=5,
                    ),
                ),
                ("target_duration", models.IntegerField(blank=True, null=True)),
                ("target_calorie", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "ExerciseTargets",
                "managed": False,
            },
        ),
    ]
