# Generated by Django 5.2.1 on 2025-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="app_id",
        ),
        migrations.AddField(
            model_name="user",
            name="open_id",
            field=models.CharField(
                blank=True,
                db_column="open_id",
                max_length=100,
                null=True,
                verbose_name="应用ID",
            ),
        ),
    ]
