# Generated by Django 5.2.3 on 2025-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_profile", "0002_remove_user_app_id_user_open_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="open_id",
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.IntegerField(
                blank=True, db_column="weight", null=True, verbose_name="体重(kg)"
            ),
        ),
    ]
