# Generated by Django 5.2.3 on 2025-06-17 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialcommentinteraction",
            options={"managed": False, "ordering": ["-interact_time"]},
        ),
        migrations.AlterModelOptions(
            name="socialmediapost",
            options={"managed": False, "ordering": ["-post_time"]},
        ),
    ]
