# Generated by Django 5.2.1 on 2025-05-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_profile', '0002_remove_user_app_id_user_open_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='帖子ID')),
                ('post_time', models.DateTimeField(auto_now_add=True, verbose_name='帖子发布时间')),
                ('post_title', models.TextField(verbose_name='帖子标题')),
                ('post_content', models.TextField(verbose_name='帖子内容')),
                ('post_image', models.JSONField(blank=True, null=True, verbose_name='帖子图片')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('verification_status', models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '未通过')], default='pending', max_length=10, verbose_name='认证状态')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='web_profile.user', verbose_name='发布用户ID')),
            ],
            options={
                'db_table': 'SocialMediaPost',
                'ordering': ['-post_time'],
            },
        ),
        migrations.CreateModel(
            name='SocialCommentInteraction',
            fields=[
                ('interact_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='父评论 ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('interact_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='web_profile.user', verbose_name='互动用户 ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment_list.socialmediapost', verbose_name='互动帖子 ID')),
            ],
            options={
                'db_table': 'SocialCommentInteraction',
                'ordering': ['-interact_time'],
            },
        ),
    ]
