# Generated by Django 5.2.3 on 2025-06-17 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gogogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciserecords",
            options={
                "managed": False,
                "verbose_name": "运动记录",
                "verbose_name_plural": "运动记录",
            },
        ),
    ]
