# Generated by Django 5.2.1 on 2025-05-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseRecords",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.IntegerField()),
                ("record_time", models.DateField()),
                ("exercise_type", models.CharField(max_length=20)),
                ("duration", models.IntegerField()),
                ("distance", models.FloatField(blank=True, null=True)),
                ("calorie", models.FloatField(blank=True, null=True)),
                (
                    "verification_photo_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ExerciseRecords",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("record_date", models.DateField()),
                ("total_duration", models.IntegerField(default=0)),
                ("total_calorie", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-record_date"],
                "unique_together": {("uid", "record_date")},
            },
        ),
    ]
