# Generated by Django 5.2.1 on 2025-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_start", models.DateField()),
                ("uid", models.IntegerField()),
                ("total_duration", models.IntegerField(default=0)),
                ("total_calorie", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-month_start", "-total_calorie"],
                "unique_together": {("month_start", "uid")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("uid", models.IntegerField()),
                ("total_duration", models.IntegerField(default=0)),
                ("total_calorie", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-week_start", "-total_calorie"],
                "unique_together": {("week_start", "uid")},
            },
        ),
    ]
